README.md
doc/fyler.txt
lua/fyler/config.lua
lua/fyler/views/explorer/actions.lua

feat: Add `auto_confirm_simple_edits` to config options

---

README.md
doc/fyler.txt
lua/fyler.lua
lua/fyler/autocmds.lua
lua/fyler/config.lua
lua/fyler/integrations/icon/init.lua
lua/fyler/integrations/icon/nvim-web-devicons.lua
lua/fyler/lib/fs.lua
lua/fyler/lib/hls.lua
lua/fyler/views/explorer/actions.lua
lua/fyler/views/explorer/ui.lua

feat: Add `on_highlights` options to allow highlight groups override

---

lua/fyler/lib/git.lua
lua/fyler/views/explorer/ui.lua

fix: Allow `git status` for sub directories

---

lua/fyler/integrations/icon/init.lua
lua/fyler/lib/fs.lua
lua/fyler/lib/hls.lua
lua/fyler/views/explorer/actions.lua
lua/fyler/views/explorer/ui.lua

[FIX] Icon fallback to icon provider

---

lua/fyler/autocmds.lua
lua/fyler/lib/win.lua
lua/fyler/views/explorer/actions.lua
lua/fyler/views/explorer/init.lua

[FIX] Close explorer when last window

---

README.md

docs: Add link to stable version documentation page

---

lua/fyler/autocmds.lua
lua/fyler/lib/win.lua

[FIX] Force concealing of meta info with user auto command

---

lua/fyler/views/explorer/algos.lua

fix: Add nil safety to `vim.list.unique`

---

lua/fyler.lua
lua/fyler/autocmds.lua
lua/fyler/config.lua
lua/fyler/integrations/icon.lua
lua/fyler/lib/async.lua
lua/fyler/lib/fs.lua
lua/fyler/lib/git.lua
lua/fyler/lib/hls.lua
lua/fyler/lib/structs/list.lua
lua/fyler/lib/structs/queue.lua
lua/fyler/lib/structs/stack.lua
lua/fyler/lib/ui/components.lua
lua/fyler/lib/ui/init.lua
lua/fyler/lib/util.lua
lua/fyler/lib/win.lua
lua/fyler/views/confirm/init.lua
lua/fyler/views/confirm/ui.lua
lua/fyler/views/explorer/actions.lua
lua/fyler/views/explorer/algos.lua
lua/fyler/views/explorer/init.lua
lua/fyler/views/explorer/struct.lua
lua/fyler/views/explorer/ui.lua
plugin/fyler.lua
tests/lib/structs/test_list.lua
tests/lib/structs/test_queue.lua
tests/lib/structs/test_stack.lua
tests/lib/test_win.lua
tests/views/explorer/test_struct.lua

[FIX] Patch custom mapping randomness

---

lua/fyler/autocmds.lua
lua/fyler/lib/win.lua

[FIX] Trigger buffer tracking manually

---

Makefile
README.md
lua/fyler/config.lua
lua/fyler/lib/win.lua
lua/fyler/views/confirm/init.lua
lua/fyler/views/explorer/init.lua
tests/init.lua
tests/lib/test_win.lua

[FEAT] Better dimensions

---

README.md
lua/fyler/config.lua
lua/fyler/views/explorer/actions.lua
lua/fyler/views/explorer/init.lua
lua/fyler/views/explorer/store.lua
lua/fyler/views/explorer/struct.lua

- `GotoParent` to navigate to parent directory
- `GotoCwd` to navigate to current working directory
resolves: #97

[FEAT] Navigation actions

---

README.md
doc/fyler.txt
lua/fyler/config.lua
lua/fyler/views/explorer/actions.lua

[FEAT] `GotoNode` action

---

README.md
doc/fyler.txt
lua/fyler.lua
lua/fyler/config.lua
lua/fyler/hooks.lua
lua/fyler/lib/fs.lua

LSP Renaming attached to `on_rename` hooks
resolves: #69

feat(hooks): Implement customizable hooks

---

lua/fyler/views/explorer/actions.lua

[FIX] Cache `undolevels` for better control

---

README.md
doc/fyler.txt
lua/fyler.lua
lua/fyler/autocmds.lua
lua/fyler/config.lua

[FEAT] Implement `track_buffer` API

---

lua/fyler/lib/win.lua

[FIX] Focus on existing same explorer instance

---

README.md
doc/fyler.txt
lua/fyler/config.lua
lua/fyler/explorer/ui.lua

[FEAT] Add custom icons for various directory states

---

lua/fyler/explorer.lua
lua/fyler/explorer/actions.lua

[FIX] Fyler file selection

---

README.md
doc/fyler.txt
lua/fyler/config.lua
lua/fyler/lib/popup.lua
lua/fyler/popups/permission/init.lua

[FEAT] Popups configuration

---

lua/fyler.lua

[FEAT] Implement `toggle` API

---

lua/fyler.lua

[FIX] Handle protocol path in toggle API
